package in.ovtech.ndtower.helper;

import android.content.Context;

import java.util.ArrayList;

import in.ovtech.ndtower.Person;

/**
 * Created by pranay on 28/4/15.
 */
public class PersonNames {

    String[] names ={"Abraham K P",
            "Vindula Vyawahare",
            "Ghugare B G",
            "Kamble B V",
            "Pravin Kumar",
            "Alias Kripa",
            "Lili Paul",
            "Lili Paul",
            "Sarda Rahul",
            "Dias",
            "Shewale Sunil",
            "Arvind Pandhare",
            "Dr R K Mutha",
            "Geeta Carrasco",
            "Sudhir Kothari",
            "Jagannath Rao",
            "Rekha Kapse",
            "Nitesh Nanaware",
            "Nikhil Rajendra Kataria",
            "Ashish Pitale",
            "Pandu Rang",
            "Swastik Tripathi",
            "Sunil Muley",
            "C P Jojo",
            "Wanjari Lalit",
            "Kulkarni Anil",
            "Uday Thakare",
            "Thakur Pradip",
            "Shrikant Bhope",
            "Shashikant Bhope",
            "Sneha Sawant",
            "Pattnaik Happy",
            "Muhammed baig",
            "Priya Ranjan",
            "George / Oomen Mini",
            "Imran Khan",
            "Haji Saftulla Choudhry ",
            "Parwez Khan",
            "Sanjay Chandra",
            "Sagar Jadhav",
            "Muzammil Shaikh",
            "Harinarayanan K",
            "Chaudhry",
            "Sohail Shaikh",
            "Subhash Gajare",
            "Salhuddin Khan",
            "Sutanabegam Khan",
            "Naresh Mehta",
            "Kanilal Jain",
            "Bhushan Vaidya",
            "Nazma Chaudhary",
            "Vijay Adaskar",
            "Vijay Adaskar",
            "Anjali Adaskar",
            "Prithivaraj Patil",
            "Shankar Ghadage",
            "Swati Kalbhor",
            "Sanjay Kalbhor",
            "Bhupendra Bora",
            "Sarjairao Mali ",
            "Sabiha More",
            "Abhay Bhadbhade",
            "Himanshu Maheshwari",
            "Shaukat Khan",
            "Kiswar Jahan",
            "K Anil Kumar",
            "Abhaysingh Rajput",
            "Suraiyya Mahaboob shaikh",
            "Sampath Pawar",
            "Rajkumar Munot",
            "Biswa Pattanayak",
            "Shalinee Agolla",
            "Shabana Memon",
            "Imran Ahmed Shaikh",
            "Abdul Q Shaikh",
            "Misabah Uddin",
            "Shaikh Ali",
            "Vijaykumar Ashtekar",
            "Naveed Jamadar",
            "Bharat Jadhav",
            "Jitendra Hingmire",
            "Asif Iqbal Mulla",
            "Rajendra Kharade",
            "Khalid Qumar",
            "Hamid Qumar",
            "Rafikul Islam",
            "Nadeem Shaikh",
            "No Sale",
            "Anil Gaikwad",
            "Amit Bhalagat",
            "Munir Shah",
            "Pranay Kadu",
            "Asifali Saiyed",
            "Anuradha Dixit",
            "Sunil Kote",
            "S K Mulla"
    };

public String[] allFlats  = { "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','101','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','102','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','103','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','104','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','105','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','201','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','202','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','203','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','204','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','205','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','206','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','301','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','302','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','303','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','304','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','305','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','401','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','402','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','403','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','404','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','405','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','406','','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','501','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','502','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','503','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','504','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','505','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','601','','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','602','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','603','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','604','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','605','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','701','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','702','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','703','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','704','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','705','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','801','YES','vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','802','','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','803','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','804','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','','','vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','901','','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','902','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','903','','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','904','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','905','YES','vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1001','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1002','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1003','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1004','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1005','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1101','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1102','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1103','','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1104','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1105','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1201','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1202','','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1203','','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1204','YES','Self ')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values ( 'B','1205','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','101','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','102','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','103','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','104','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','105','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','201','Yes','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','202','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','203','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','204','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','205','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','301','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','302','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','303','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','304','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','305','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','401','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','402','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','403','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','404','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','405','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','501','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','502','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','503','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','504','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','505','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','601','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','602','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','603','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','604','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','605','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','701','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','702','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','703','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','704','YES','Vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','705','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','801','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','802','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','803','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','804','YES','')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','805','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','901','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','902','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','903','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','904','YES','Vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','905','','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1001','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1002','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1003','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1004','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1005','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1101','YES','Rented')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1102','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1103','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1104','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1105','','Vacant')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1201','','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1202','YES','Rent')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1203','YES','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1204','','Self')",
        "Insert into NDFLAT (wing,flatno, possesion,status) values (  'A','1205','',)"


} ;

    public String[] updateAllFlatswithmapID={"Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','204','2','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','304','3','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','101','4','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1202','5','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','201','6','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','802','7','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','801','8','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1205','9','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','903','10','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','302','11','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','405','12','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','604','13','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','902','14','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','602','15','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','105','16','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1104','17','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','403','18','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','503','19','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1001','20','YES','vacant')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1103','21','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1104','21','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1105','21','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1204','21','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1205','21','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','205','22','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','303','23','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1102','24','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','304','25','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','705','26','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','103','27','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','802','28','','vacant')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','702','29','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','905','30','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','205','31','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','501','32','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','801','33','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','401','34','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','603','35','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','303','36','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','104','37','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1102','38','YES','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','701','39','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','302','40','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','505','41','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','202','42','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','203','42','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1002','43','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1004','44','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1005','44','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','503','45','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1203','46','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','703','47','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','803','48','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','804','48','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','904','49','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','704','50','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1101','51','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','601','52','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1105','53','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','404','54','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','403','55','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','406','56','','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','803','57','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','702','58','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','901','59','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','105','60','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','101','61','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','704','62','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','703','63','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','605','64','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','402','65','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','805','66','','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','402','67','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1001','68','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','203','69','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','902','70','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1004','71','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','401','72','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','804','73','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','104','74','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','204','75','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1101','76','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','201','77','Yes','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','405','78','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','504','79','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','404','80','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1003','81','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','102','82','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','605','83','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','301','84','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','301','85','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','604','86','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','701','87','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1002','88','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1003','89','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','305','90','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','904','91','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','502','92','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','202','93','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','305','94','','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1005','95','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','501','96','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','103','97','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','603','98','YES','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','602','99','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1201','100','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1204','100','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','505','101','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','102','102','YES','Rented')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','504','103','YES','Self ')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','206','104','YES','Self')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','601','105','','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','901','106','','vacant')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','903','107','','Rent')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1103','108','','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1202','109','','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('B','1203','110','','')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','905','111','','Vacant')",
            "Insert into NDFLAT (wing,flatno, ownerid,possesion,status) values('A','1201','112','','Vacant')"};

public String[] allPersonsdetail={"Insert into NDPERSON (mapid,name, mobile) values('1','Abdul Q Shaikh','DO    ')",
        "Insert into NDPERSON (mapid,name, mobile) values('2','Abhay Bhadbhade','9422040581')",
        "Insert into NDPERSON (mapid,name, mobile) values('3','Abhaysingh Rajput','9890128376')",
        "Insert into NDPERSON (mapid,name, mobile) values('4','Abraham K P','9552626765')",
        "Insert into NDPERSON (mapid,name, mobile) values('5','Abusalman Jawed Khan','')",
        "Insert into NDPERSON (mapid,name, mobile) values('6','Alias Kripa','9673901363')",
        "Insert into NDPERSON (mapid,name, mobile) values('7','Amit Bhalagat','9850998234')",
        "Insert into NDPERSON (mapid,name, mobile) values('8','Anil Gaikwad','9623453327')",
        "Insert into NDPERSON (mapid,name, mobile) values('9','Anjali Adaskar','9422326477')",
        "Insert into NDPERSON (mapid,name, mobile) values('10','Anuradha Dixit','9594466777')",
        "Insert into NDPERSON (mapid,name, mobile) values('11','Arvind Pandhare','9730472193')",
        "Insert into NDPERSON (mapid,name, mobile) values('12','Ashish Pitale','9730312349')",
        "Insert into NDPERSON (mapid,name, mobile) values('13','Asif Iqbal Mulla','9623987917')",
        "Insert into NDPERSON (mapid,name, mobile) values('14','Asifali Saiyed','9028011665')",
        "Insert into NDPERSON (mapid,name, mobile) values('15','Bharat Jadhav','9970005975')",
        "Insert into NDPERSON (mapid,name, mobile) values('16','Bhupendra Bora','9890030169')",
        "Insert into NDPERSON (mapid,name, mobile) values('17','Bhushan Vaidya','9225514826')",
        "Insert into NDPERSON (mapid,name, mobile) values('18','Biswa Pattanayak','9011085130')",
        "Insert into NDPERSON (mapid,name, mobile) values('19','C P Jojo','9422310898')",
        "Insert into NDPERSON (mapid,name, mobile) values('20','Chaudhry','9764394458')",
        "Insert into NDPERSON (mapid,name, mobile) values('21','D N Kalbhor','9960111222')",
        "Insert into NDPERSON (mapid,name, mobile) values('21','D N Kalbhor','9960111222')",
        "Insert into NDPERSON (mapid,name, mobile) values('21','D N Kalbhor','9960111222')",
        "Insert into NDPERSON (mapid,name, mobile) values('21','D N Kalbhor','9960111222')",
        "Insert into NDPERSON (mapid,name, mobile) values('21','D N Kalbhor','9960111222')",
        "Insert into NDPERSON (mapid,name, mobile) values('22','Dias','9881714657')",
        "Insert into NDPERSON (mapid,name, mobile) values('23','Dr R K Mutha','9422237872')",
        "Insert into NDPERSON (mapid,name, mobile) values('24','Fatima Shaikh','9987081308')",
        "Insert into NDPERSON (mapid,name, mobile) values('25','Geeta Carrasco','9545451761')",
        "Insert into NDPERSON (mapid,name, mobile) values('26','George / Oomen Mini','9422515380')",
        "Insert into NDPERSON (mapid,name, mobile) values('27','Ghugare B G','9881426814')",
        "Insert into NDPERSON (mapid,name, mobile) values('28','Haji Saftulla Choudhry ','8983697795')",
        "Insert into NDPERSON (mapid,name, mobile) values('29','Hamid Qumar','9823216736')",
        "Insert into NDPERSON (mapid,name, mobile) values('30','Harinarayanan K','9373937303')",
        "Insert into NDPERSON (mapid,name, mobile) values('31','Himanshu Maheshwari','9890374584')",
        "Insert into NDPERSON (mapid,name, mobile) values('32','Imran Ahmed Shaikh','9823425086')",
        "Insert into NDPERSON (mapid,name, mobile) values('33','Imran Khan','')",
        "Insert into NDPERSON (mapid,name, mobile) values('34','Jagannath Rao','8600922235')",
        "Insert into NDPERSON (mapid,name, mobile) values('35','Jitendra Hingmire','9850950013')",
        "Insert into NDPERSON (mapid,name, mobile) values('36','K Anil Kumar','9373229829')",
        "Insert into NDPERSON (mapid,name, mobile) values('37','Kamble B V','9766333620')",
        "Insert into NDPERSON (mapid,name, mobile) values('38','Kanilal Jain','')",
        "Insert into NDPERSON (mapid,name, mobile) values('39','Khalid Qumar','9823216736')",
        "Insert into NDPERSON (mapid,name, mobile) values('40','Kiswar Jahan','    do')",
        "Insert into NDPERSON (mapid,name, mobile) values('41','Kulkarni Anil','9820409400')",
        "Insert into NDPERSON (mapid,name, mobile) values('42','Lili Paul','2027240073')",
        "Insert into NDPERSON (mapid,name, mobile) values('42','Lili Paul','9920515605')",
        "Insert into NDPERSON (mapid,name, mobile) values('43','Md. Zakir Ahmed','9765409549')",
        "Insert into NDPERSON (mapid,name, mobile) values('44','Mirza Hasnat Baig','9970129192')",
        "Insert into NDPERSON (mapid,name, mobile) values('44','Mirza Hasnat Baig','9860112828 / 9881700683')",
        "Insert into NDPERSON (mapid,name, mobile) values('45','Misabah Uddin','9970136615')",
        "Insert into NDPERSON (mapid,name, mobile) values('46','Mohammed Usman Jawed Khan','8421580390')",
        "Insert into NDPERSON (mapid,name, mobile) values('47','Muhammed baig','9960115090')",
        "Insert into NDPERSON (mapid,name, mobile) values('48','Munir Shah','9561697880')",
        "Insert into NDPERSON (mapid,name, mobile) values('48','Munir Shah','9561697880')",
        "Insert into NDPERSON (mapid,name, mobile) values('49','Muzammil Shaikh','9762303270')",
        "Insert into NDPERSON (mapid,name, mobile) values('50','Nadeem Shaikh','9892068172')",
        "Insert into NDPERSON (mapid,name, mobile) values('51','Naresh Mehta','8888835410')",
        "Insert into NDPERSON (mapid,name, mobile) values('52','Naveed Jamadar','9822207856')",
        "Insert into NDPERSON (mapid,name, mobile) values('53','Nazma Chaudhary','9764394458')",
        "Insert into NDPERSON (mapid,name, mobile) values('54','Nikhil Rajendra Kataria','9423162432')",
        "Insert into NDPERSON (mapid,name, mobile) values('55','Nitesh Nanaware','9371135516')",
        "Insert into NDPERSON (mapid,name, mobile) values('56','Pandu Rang','9823406581')",
        "Insert into NDPERSON (mapid,name, mobile) values('57','Parwez Khan','9011937577')",
        "Insert into NDPERSON (mapid,name, mobile) values('58','Pattnaik Happy','9028878165')",
        "Insert into NDPERSON (mapid,name, mobile) values('59','Pranay Kadu','8928136883')",
        "Insert into NDPERSON (mapid,name, mobile) values('60','Pravin Kumar','9371034068')",
        "Insert into NDPERSON (mapid,name, mobile) values('61','Prithivaraj Patil','9822065756')",
        "Insert into NDPERSON (mapid,name, mobile) values('62','Priya Ranjan','9586979551')",
        "Insert into NDPERSON (mapid,name, mobile) values('63','Rafikul Islam','9689881988')",
        "Insert into NDPERSON (mapid,name, mobile) values('64','Rajendra Kharade','8975758162')",
        "Insert into NDPERSON (mapid,name, mobile) values('65','Rajkumar Munot','9881491908')",
        "Insert into NDPERSON (mapid,name, mobile) values('66','REFUGE AREA','')",
        "Insert into NDPERSON (mapid,name, mobile) values('67','Rekha Kapse','9890623382')",
        "Insert into NDPERSON (mapid,name, mobile) values('68','S K Mulla','9923562926')",
        "Insert into NDPERSON (mapid,name, mobile) values('69','Sabiha More','8793720655')",
        "Insert into NDPERSON (mapid,name, mobile) values('70','Sagar Jadhav','8888899175')",
        "Insert into NDPERSON (mapid,name, mobile) values('71','Salhuddin Khan','9890033816')",
        "Insert into NDPERSON (mapid,name, mobile) values('72','Sampath Pawar','9922238318')",
        "Insert into NDPERSON (mapid,name, mobile) values('73','Sanjay Chandra','9850049959')",
        "Insert into NDPERSON (mapid,name, mobile) values('74','Sanjay Kalbhor','9158567744')",
        "Insert into NDPERSON (mapid,name, mobile) values('75','Sarda Rahul','9860484082')",
        "Insert into NDPERSON (mapid,name, mobile) values('76','Sarfaraz Shaikh','9987081308')",
        "Insert into NDPERSON (mapid,name, mobile) values('77','Sarjairao Mali ','9623163219')",
        "Insert into NDPERSON (mapid,name, mobile) values('78','Shabana Memon','9922374660')",
        "Insert into NDPERSON (mapid,name, mobile) values('79','Shaikh Ali','9920835658')",
        "Insert into NDPERSON (mapid,name, mobile) values('80','Shalinee Agolla','9822694151')",
        "Insert into NDPERSON (mapid,name, mobile) values('81','Shamimuddin','9892128687')",
        "Insert into NDPERSON (mapid,name, mobile) values('82','Shankar Ghadage','9892025677')",
        "Insert into NDPERSON (mapid,name, mobile) values('83','Shashikant Bhope','9822783117')",
        "Insert into NDPERSON (mapid,name, mobile) values('84','Shaukat Khan','9890222299')",
        "Insert into NDPERSON (mapid,name, mobile) values('85','Sunil Shewale','9689889210')",
        "Insert into NDPERSON (mapid,name, mobile) values('86','Shrikant Bhope','9881716861')",
        "Insert into NDPERSON (mapid,name, mobile) values('87','Sneha Sawant','9689885721')",
        "Insert into NDPERSON (mapid,name, mobile) values('88','Sohail Shaikh','9922661655')",
        "Insert into NDPERSON (mapid,name, mobile) values('89','Subhash Gajare','8605871400')",
        "Insert into NDPERSON (mapid,name, mobile) values('90','Sudhir Kothari','9890270985')",
        "Insert into NDPERSON (mapid,name, mobile) values('91','Sunil Kote','9890996181')",
        "Insert into NDPERSON (mapid,name, mobile) values('92','Sunil Muley','9860059082')",
        "Insert into NDPERSON (mapid,name, mobile) values('93','Sunil Shewale','9689889210')",
        "Insert into NDPERSON (mapid,name, mobile) values('94','Suraiyya Mahaboob shaikh','9822026733')",
        "Insert into NDPERSON (mapid,name, mobile) values('95','Sutanabegam Khan','9890033816')",
        "Insert into NDPERSON (mapid,name, mobile) values('96','Swastik Tripathi','9922958202')",
        "Insert into NDPERSON (mapid,name, mobile) values('97','Swati Kalbhor','9158567744')",
        "Insert into NDPERSON (mapid,name, mobile) values('98','Thakur Pradip','9689787863')",
        "Insert into NDPERSON (mapid,name, mobile) values('99','Uday Thakare','9973400474')",
        "Insert into NDPERSON (mapid,name, mobile) values('100','Vijay Adaskar','9422326477')",
        "Insert into NDPERSON (mapid,name, mobile) values('100','Vijay Adaskar','9422326477')",
        "Insert into NDPERSON (mapid,name, mobile) values('101','Vijaykumar Ashtekar','9371276538')",
        "Insert into NDPERSON (mapid,name, mobile) values('102','Vindula Vyawahare','9860996449')",
        "Insert into NDPERSON (mapid,name, mobile) values('103','Wanjari Lalit','9975606613')",
        "Insert into NDPERSON (mapid,name, mobile) values('104',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('105',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('106',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('107',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('108',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('109',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('110',' no detail','')",
        "Insert into NDPERSON (mapid,name, mobile) values('111','no  details','')",
        "Insert into NDPERSON (mapid,name, mobile) values('112','no  details','')",
        "Insert into NDPERSON (mapid,name, mobile,ownerid) values('113','Sunil a tenant','986082',93)",
        "Insert into NDPERSON (mapid,name, mobile,ownerid) values('114','Sunil Kote a tenant','986082',93)"
};

    public String[] tenantList ={
            "Insert into NDPERSON (mapid,name, mobile,ownerid) values('113','Sunil a tenant','986082',93)",
    };

    public void insertData(Context context){
    SQLiteHandler db =  new SQLiteHandler(context );

    for(int i=0;i < names.length ; i++)
    {

        Person person =new Person();
        person.set_name(names[i]);
        db.addPerson(person);
    }


}

    public void insertAllFlats(Context context){
        SQLiteHandler db =  new SQLiteHandler(context );

        for(int i=0;i < allFlats.length ; i++)
        {
            db.executeQuery(allFlats[i]);

        }
    }
    public void deleteData(Context context){


        for(int i=0;i < names.length ; i++)
        {
            SQLiteHandler db =  new SQLiteHandler(context );
            String query ="delete from  NDPERSON " ; //where name ='" +names[i]+ "'";
            db.executeQuery(query);
        }


    }


}
